version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: postgres-technical-test-kma
    restart: "no"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=technical_test_kma
    ports:
      - "5433:5432"
    networks:
      - docker

networks:
  docker:
